### ISSUE TITLE
Planning to use this

### ISSUE THREAD

**Issue by unstoppablecarl** [jrop/nedb-promise#1]
I am planning to use this for a project. Are you still maintaining it? Would you accept pull requests?

I would like to add the ability to pass an options object to `Promise.promisifyAll` https://github.com/jrop/nedb-promise/blob/master/src/index.js#L6

This line in the readme example code `let DB = new datastore(..` should not have `new`.

**Comment by jrop** [comment]
Yes I would accept a pull request.  Thanks for your interest!

**Comment by jrop** [comment]
One thing I was investigating for the next version is whether to switch to using `thenify` + `thenify-all` for the promisification.  The thought is that they would be much lighter dependencies than bluebird.

**Comment by jrop** [comment]
I just pushed up some stuff: 1) I removed the dependency on Babel, 2) I switched to using `thenify` instead of `bluebird`; what was the feature you wanted to use when passing options to promisifyAll?  Did you want to define your own suffix?

**Comment by unstoppablecarl** [comment]
I really wanted no suffix so bluebird required one thenify is perfect because it does not. So adding the option to set the suffix would be needed.

I would also like to be able to pass an instance of `new NedbDatastore(options)` to be thenified so that I could make changes to the object before it is processed. 

Should I make a PR for these?

**Comment by unstoppablecarl** [comment]
I just tried out the new code. It does not work if you remove the suffix :disappointed: . 

I am considering using this. It gives the end result I am looking for but does seem kinda heavy and requires me to fix the cursor returns.

```js
var PromisifyMe = require('promisify-me');
var nedb = PromisifyMe(require('nedb'), 'nedb');

nedb.prototype.findC = nedb.prototype.find;
nedb.prototype.find = function(query, projection){
    var cursor = this.findC(query, projection);
    return cursor.exec();
};

nedb.prototype.findOneC = nedb.prototype.findOne;
nedb.prototype.findOne = function(query, projection){
    var cursor = this.findOneC(query, projection);
    return cursor.exec();
};

module.exports = nedb;
```

**Comment by jrop** [comment]
Well, the issue with this is that if we want a completely authentic promisified API it will indeed be a bit heavy to implement.  Using promisifiers is always going to leave this feeling slightly half-baked.  I may look into doing this and seeing how I'm depth it is.

**Comment by jrop** [comment]
@unstoppablecarl 

I currently have changed my wrapper to this on my dev machine, and it seems to work, and be what you want, would you mind testing?:

```js
var NedbDatastore = require('nedb')
var thenify = require('thenify')

function datastore(options) {
	var DB = new NedbDatastore(options)
	var newDB = { nedb: DB }

	var methods = [ 'loadDatabase', 'insert', 'find', 'findOne', 'count', 'update', 'remove', 'ensureIndex', 'removeIndex' ]
	for (var i = 0; i < methods.length; ++i) {
		var m = methods[i]
		newDB[m] = thenify(DB[m].bind(DB))
	}

	newDB.cfind = function(query) {
		var c = DB.find(query)
		c.exec = thenify(c.exec.bind(c))
		return c
	}

	newDB.cfindOne = function(query) {
		var c = DB.findOne(query)
		c.exec = thenify(c.exec.bind(c))
		return c
	}

	newDB.ccount = function(query) {
		var c = DB.count(query)
		c.exec = thenify(c.exec.bind(c))
		return c
	}

	return newDB
}

// so that import { datastore } still works:
datastore.datastore = datastore

module.exports = datastore
```

**Comment by unstoppablecarl** [comment]
Sure. @jrop might be easier to chat realtime. You can message me on hangouts using the email in my profile.

**Comment by jrop** [comment]
Alright, per our conversation I've published a new version on NPM.  I don't think a lot of people are using this library so I just bumped the version number (probably a bad idea, crossing my fingers).  Closing this issue for now.

**Comment by jrop** [comment]
@unstoppablecarl I had an issue open up that the major version number not getting bumped was causing problems, I have since put these changes under 2.x, so you may need to update your package.json to depend on `"nedb-promise": "^2.0.0"`.

**Comment by unstoppablecarl** [comment]
Np. I did warn you :smile:
