### ISSUE TITLE
Bump major version for non-backwards compatible api changes

### ISSUE THREAD

**Issue by ylambda** [jrop/nedb-promise#2]
The recent changes in b09020e1e6ce64bfdabe83fbfa0b67c4f593ccc8 change the api in a non-backwards compatible way.

Please bump the package.json major version to prevent erorrs when installing this as dependency with `^1.0.0` specified as the version. I believe this is the default semantic version npm uses.

**Comment by jrop** [comment]
Crap, sorry about that, I will put two commits in shortly...one reverting that (1.0.4), and one for the new API (2.0.0)

**Comment by jrop** [comment]
I have just published 1.0.4, and 2.0.0 to npm, can you confirm 1.0.4 now works with your project?

**Comment by ylambda** [comment]
Yep. `1.0.4` works. I'll be sure to update to `2.0.0` soon. Thanks.
