### ISSUE TITLE
Datastore.persistence is undefined.

### ISSUE THREAD

**Issue by apboon** [jrop/nedb-promise#6]
Datastore.persistence is undefined, therefore can't do NeDB documented functions like Datastore.persistence.compactDatafile();

Was not able to find temporary workaround unlike the very similar library "nedb-promises" (extra "s"), which allows Datastore.__original.persistence.compactDatafile(); etc.

Reported this problem to both "nedb-promise" and "nedb-promises" projects. Similar project, similar problem :)

Although the code of the "nedb-promise" version (this version) looks better.

**Comment by jrop** [comment]
Yes, datastore loosely follows nedb's implementation.  It is not an exact representation.  If you want to control the underlying datastore, create it as regular using the original nedb library, and then create a wrapped version:

```js
const nedb = require('nedb')
const nedbP = require('nedb-promise')

const ds = nedb(...)
const db = nedbP.fromInstance(ds)
```

Typed this from my phone so please validate against the docs...

**Comment by jrop** [comment]
@apboon 
To elaborate on the previous comment, you can do something like this:

```js
const Datastore = require('nedb')
const nedbPromise = require('nedb-promise')

const store = Datastore({autoload: true, filename: '...'})
const db = nedbPromise.fromInstance(store)
await db.insert(...)
store.persistence.compactDatafile()
```

**Comment by apboon** [comment]
That is a great workaround in deed. I overlooked thst part/feature as I was a bit more familiar with the other similar library.. All-in-all, the code andere solutions of this library is better I think.
Thanx for your reply man! Cheers! :)
